AWSTemplateFormatVersion: '2010-09-09'
Description: DevVpc Stack

Parameters:
  OpenVpnVpcCidrBlock:
    Type: String
    Default: 10.0.0.0/24 #10.0.0.0 - 10.0.0.255
    MinLength: '9'
    MaxLength: '18'
    Description: CidrBlock for DevVpc Vpc
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  DevVpcCidrBlock:
    Type: String
    Default: 10.1.0.0/16 #10.1.0.0 - 10.1.255.255
    MinLength: '9'
    MaxLength: '18'
    Description: CidrBlock for DevVpc Vpc
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:

  DevVpcPrivateNACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId:  !ImportValue DevVpc
      Tags:
        - Key: Name
          Value: DevVpcPrivateNACL
        - Key: Stack
          Value: !Ref AWS::StackId
          
# Allows inbound SSH traffic to the subnet from your OpenVPN VPC
  SshInFromOpenVpnVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DevVpcPrivateNACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: !Ref OpenVpnVpcCidrBlock
      PortRange:
        From: '22'
        To: '22'      
        
# Allows inbound return traffic from requests originating from your OpenVPN VPC.
  AllInboundFromOpenVpnVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DevVpcPrivateNACL
      RuleNumber: '110'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: !Ref OpenVpnVpcCidrBlock
      PortRange:
        From: '32768'
        To: '65535'    

# Allows inbound from requests originating Public Subnets within VPC on Port 80 - adjust as required.
  80InboundFromOpenVpnVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DevVpcPrivateNACL
      RuleNumber: '120'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: !Ref OpenVpnVpcCidrBlock
      PortRange:
        From: '80'
        To: '80'    

# Allows all outbound traffic from from your OpenVPN VPC.
  AllOutboundToOpenVpnVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Egress: 'true'
      RuleNumber: '100'
      NetworkAclId: !Ref DevVpcPrivateNACL
      Protocol: "-1"
      RuleAction: allow
      Egress: 'true'
      CidrBlock: !Ref OpenVpnVpcCidrBlock
      
# Allows inbound return traffic from requests originating Public Subnets within VPC.
  AllOutboundToDevPublicSubnets:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DevVpcPrivateNACL
      Egress: 'true'
      RuleNumber: '110'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: !Ref DevVpcCidrBlock
      PortRange:
        From: '32768'
        To: '65535'    
          
  PrivateSubnetANetworkNaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:  !ImportValue DevVpcPrivateSubnetA
      NetworkAclId: !Ref DevVpcPrivateNACL
      
  PrivateSubnetBNetworkNaclAssociation: 
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue DevVpcPrivateSubnetB
      NetworkAclId: !Ref DevVpcPrivateNACL

      